name: Release

on:
  push:
    tags:
      - "20*"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cmake . -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
    - name: build
      run: cmake --build . --config Release
    - name: build-musl
      if: runner.os == 'Linux'
      run: |
        rm CMakeCache.txt
        mv AtomicParsley AtomicParsleyLinux
        docker run --rm -v "$(pwd):/mnt" -w '/mnt' alpine sh -c "\
          apk add cmake build-base linux-headers zlib-dev && \
          cmake . && \
          cmake --build . --config Release \
        "
    - name: zip
      if: runner.os == 'macOS'
      run: zip AtomicParsleyMacOS.zip AtomicParsley
    - name: zip
      if: runner.os == 'Linux'
      run: |
        zip AtomicParsleyAlpine.zip AtomicParsley
        mv AtomicParsleyLinux AtomicParsley
        zip AtomicParsleyLinux.zip AtomicParsley
    - name: zip
      if: runner.os == 'Windows'
      run: |
        pushd Release
        7z a -tzip ../AtomicParsleyWindows.zip AtomicParsley.exe
        popd
    - name: build-windows-x86
      if: runner.os == 'Windows'
      run: |
        rm CMakeCache.txt
        cmake -S . -B build-windows-x86 -A Win32 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
        cmake --build build-windows-x86 --config Release
        pushd build-windows-x86/Release
        7z a -tzip ../../AtomicParsleyWindowsX86.zip AtomicParsley.exe
        popd
    - name: "Upload to Tagged Release"
      uses: softprops/action-gh-release@v1
      with:
         files: "AtomicParsley*.zip"
      env:
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
